### ISSUE TITLE
Implement an add feature to add a file to cinitpp without editing the config file or copying a directory. 

### ISSUE THREAD

**Issue by Renjian-buchai** [Renjian-buchai/cinitpp#11]
### Usage

```ps
cinitpp -A test.txt
```

will create a file called test.txt in the home directory. 

The .cinitpp.json file will automatically be created, including the test.txt file in the configuration. 

If a .cinitpp.json file already exists, it will read the file, update it, and regenerate the file.

**Comment by BenjaminCole1** [comment]
this is a comment

**Comment by Renjian-buchai** [comment]
No longer relevant.
